version: "3"
services:
  grpc-server:
    build:
      context: ./src/grpc/example/
      dockerfile: ./server/Dockerfile
    image: kevin234kevin999/grpcbackend:3.1
    stdin_open: true
    tty: true
    environment:
      grpcid: "http://0.0.0.0"
    ports:
      - "7799:9988"
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: kevin234kevin999/gatewaycs:3.1
    stdin_open: true
    tty: true
    environment:
      forwardbackend: "http://www.google.com"
    ports:
      - "8090:8080"
#    volumes:
#      - ./logs:/logs
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: kevin234kevin999/fasthttpserver:1.0.0
    stdin_open: true
    tty: true
    ports:
      - "8091:8080"
#    volumes:
#      - ./logs:/logs
